### PR TITLE
Added missing dependencies

### PR DESCRIPTION
**Pull request by rkj**
Without them there were errors installing jenkins.
Best regards & thanks for great cookbook :)

### CODE REVIEW

**Comment by fnichol** [comment]
Thanks for the fixes! What platform(s) are you targeting primarily? The opscode java cookbook was a bit limited for non-openjdk solutions so I've been trying to figure out ways around that.

**Comment by rkj** [comment]
I am using plain vanilla openjdk on ubuntu. I have suspected you did not comment java depenedency by accident ;-) But maybe some ifs/attribute checks would be better, because without java there is a bit of a problem :P

**Comment by fnichol** [comment]
The include_recipe "java" shows up later in a platform?("ubuntu") block:

https://github.com/fnichol/chef-jenkins/blob/master/recipes/default.rb#L103

This repo is a fork from dougm's hudson cookbook (https://github.com/dougm/site-cookbooks) and I'm guessing it was included in that order because the opscode java cookbook favors ubuntu (which is what I'm also using by default). You're right though, java's a pretty important pre-requisite :)

**Comment by rkj** [comment]
Oh, I have missed it, sorry :) So the first uncommented include should be definitely deleted...

**Comment by fnichol** [comment]
Good call, done :)

**Pull request merged**
